/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mac.care_point.transaction.attendance;

import com.mac.care_point.transaction.attendance.model.attendanceMixModel;
import com.mac.care_point.transaction.finger_print.model.TFingerPrint;
import java.util.Date;
import java.util.List;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

/**
 *
 * @author 'Kasun Chamara'
 */
public interface AttendanceRepocitory extends JpaRepository<TFingerPrint, Integer> {

//    @Query(value = "select \n"
//            + "	m_employee.index_no as em_no,\n"
//            + "	m_employee.name as employee_name,\n"
//            + "	m_employee.epf_no,\n"
//            + "	m_employee.`type` as em_type,\n"
//            + "	ras_attrecord.Clock as in_time,\n"
//            + "	(select m_branch.name from m_branch where m_branch.index_no = m_employee.branch )as payroll_branch,\n"
//            + "	(select m_branch.name from m_branch where m_branch.index_no = t_finger_print_mashine.branch )as current_branch,\n"
//            + "ras_attrecord.type as fp_type\n"
//            + "from \n"
//            + "	ras_attrecord\n"
//            + "	left JOIN m_employee on m_employee.index_no=ras_attrecord.DIN\n"
//            + "	left JOIN t_finger_print_mashine on t_finger_print_mashine.index_no=ras_attrecord.DN\n"
//            + "where t_finger_print_mashine.branch=:branch and DATE(ras_attrecord.Clock) = :date\n"
//            + "group by m_employee.index_no\n"
//            + "order by ras_attrecord.Clock", nativeQuery = true)
//    public List<Object> getAttendanceByDateAndBranch(@Param("branch") Integer branch, @Param("date") String date);
    @Query(value = "select\n"
            + "	m_employee.index_no as em_no,\n"
            + "   m_employee.name as employee_name,\n"
            + "   m_employee.epf_no as epf_no,\n"
            + "   m_employee.`type` as emp_type,\n"
            + "   (select m_branch.name from m_branch where m_branch.index_no = m_employee.branch )as payroll_branch,\n"
            + "   (select m_branch.name from m_branch where m_branch.index_no = t_finger_print_mashine.branch )as current_branch,\n"
            + "   \n"
            + "   (select ras_attrecord.Clock \n"
            + "		from ras_attrecord \n"
            + "		where m_employee.index_no=ras_attrecord.DIN \n"
            + "		and t_finger_print_mashine.index_no=ras_attrecord.DN\n"
            + "		and DATE(ras_attrecord.Clock) =:date\n"
            + "		and t_finger_print_mashine.branch=:branch \n"
            + "		order by ras_attrecord.clock limit 1) as in_time,\n"
            + "		\n"
            + "	(select ras_attrecord.type \n"
            + "		from ras_attrecord \n"
            + "		where m_employee.index_no=ras_attrecord.DIN \n"
            + "		and t_finger_print_mashine.index_no=ras_attrecord.DN\n"
            + "		and DATE(ras_attrecord.Clock) =:date\n"
            + "		and t_finger_print_mashine.branch=:branch \n"
            + "		order by ras_attrecord.clock limit 1) as in_type,\n"
            + "		\n"
            + "	(if((select count(ras_attrecord.ID )\n"
            + "		from ras_attrecord \n"
            + "		where m_employee.index_no=ras_attrecord.DIN \n"
            + "		and t_finger_print_mashine.index_no=ras_attrecord.DN\n"
            + "		and DATE(ras_attrecord.Clock) =:date\n"
            + "		and t_finger_print_mashine.branch=:branch \n"
            + "		order by ras_attrecord.clock desc)>1,(select ras_attrecord.Clock \n"
            + "		from ras_attrecord \n"
            + "		where m_employee.index_no=ras_attrecord.DIN \n"
            + "		and t_finger_print_mashine.index_no=ras_attrecord.DN\n"
            + "		and DATE(ras_attrecord.Clock) =:date\n"
            + "		and t_finger_print_mashine.branch=:branch \n"
            + "		order by ras_attrecord.clock desc limit 1),null)) as out_time,\n"
            + "		\n"
            + "		(if((select count(ras_attrecord.ID )\n"
            + "		from ras_attrecord \n"
            + "		where m_employee.index_no=ras_attrecord.DIN \n"
            + "		and t_finger_print_mashine.index_no=ras_attrecord.DN\n"
            + "		and DATE(ras_attrecord.Clock) =:date\n"
            + "		and t_finger_print_mashine.branch=:branch \n"
            + "		order by ras_attrecord.clock desc)>1,(select ras_attrecord.type \n"
            + "		from ras_attrecord \n"
            + "		where m_employee.index_no=ras_attrecord.DIN \n"
            + "		and t_finger_print_mashine.index_no=ras_attrecord.DN\n"
            + "		and DATE(ras_attrecord.Clock) =:date\n"
            + "		and t_finger_print_mashine.branch=:branch \n"
            + "		order by ras_attrecord.clock desc limit 1),null)) as out_type,\n"
            + "		ras_attrecord.DN\n"
            + "FROM \n"
            + "ras_attrecord\n"
            + "   left JOIN m_employee on m_employee.index_no=ras_attrecord.DIN\n"
            + "   left JOIN t_finger_print_mashine on t_finger_print_mashine.index_no=ras_attrecord.DN\n"
            + "   where t_finger_print_mashine.branch=:branch and DATE(ras_attrecord.Clock) =:date\n"
            + "   group by m_employee.index_no\n", nativeQuery = true)
    public List<Object> getAttendanceByDateAndBranch(@Param("branch") Integer branch, @Param("date") String date);

    @Query(value = "select\n"
            + "	m_employee.index_no as em_no,\n"
            + "   m_employee.name as employee_name,\n"
            + "   m_employee.epf_no as epf_no,\n"
            + "   m_employee.`type` as emp_type,\n"
            + "   (select m_branch.name from m_branch where m_branch.index_no = m_employee.branch )as payroll_branch,\n"
            + "   (select m_branch.name from m_branch where m_branch.index_no = t_finger_print_mashine.branch )as current_branch,\n"
            + "   \n"
            + "   (select ras_attrecord.Clock \n"
            + "		from ras_attrecord \n"
            + "		where m_employee.index_no=ras_attrecord.DIN \n"
            + "		and t_finger_print_mashine.index_no=ras_attrecord.DN\n"
            + "		and DATE(ras_attrecord.Clock) =:date\n"
            + "		and t_finger_print_mashine.branch=:branch \n"
            + "		order by ras_attrecord.clock limit 1) as in_time,\n"
            + "		\n"
            + "	(select ras_attrecord.type \n"
            + "		from ras_attrecord \n"
            + "		where m_employee.index_no=ras_attrecord.DIN \n"
            + "		and t_finger_print_mashine.index_no=ras_attrecord.DN\n"
            + "		and DATE(ras_attrecord.Clock) =:date\n"
            + "		and t_finger_print_mashine.branch=:branch \n"
            + "		order by ras_attrecord.clock limit 1) as in_type,\n"
            + "		\n"
            + "	(if((select count(ras_attrecord.ID )\n"
            + "		from ras_attrecord \n"
            + "		where m_employee.index_no=ras_attrecord.DIN \n"
            + "		and t_finger_print_mashine.index_no=ras_attrecord.DN\n"
            + "		and DATE(ras_attrecord.Clock) =:date\n"
            + "		and t_finger_print_mashine.branch=:branch \n"
            + "		order by ras_attrecord.clock desc)>1,(select ras_attrecord.Clock \n"
            + "		from ras_attrecord \n"
            + "		where m_employee.index_no=ras_attrecord.DIN \n"
            + "		and t_finger_print_mashine.index_no=ras_attrecord.DN\n"
            + "		and DATE(ras_attrecord.Clock) =:date\n"
            + "		and t_finger_print_mashine.branch=:branch \n"
            + "		order by ras_attrecord.clock desc limit 1),null)) as out_time,\n"
            + "		\n"
            + "		(if((select count(ras_attrecord.ID )\n"
            + "		from ras_attrecord \n"
            + "		where m_employee.index_no=ras_attrecord.DIN \n"
            + "		and t_finger_print_mashine.index_no=ras_attrecord.DN\n"
            + "		and DATE(ras_attrecord.Clock) =:date\n"
            + "		and t_finger_print_mashine.branch=:branch \n"
            + "		order by ras_attrecord.clock desc)>1,(select ras_attrecord.type \n"
            + "		from ras_attrecord \n"
            + "		where m_employee.index_no=ras_attrecord.DIN \n"
            + "		and t_finger_print_mashine.index_no=ras_attrecord.DN\n"
            + "		and DATE(ras_attrecord.Clock) =:date\n"
            + "		and t_finger_print_mashine.branch=:branch \n"
            + "		order by ras_attrecord.clock desc limit 1),null)) as out_type,\n"
            + "		ras_attrecord.DN\n"
            + "FROM \n"
            + "ras_attrecord\n"
            + "   left JOIN m_employee on m_employee.index_no=ras_attrecord.DIN\n"
            + "   left JOIN t_finger_print_mashine on t_finger_print_mashine.index_no=ras_attrecord.DN\n"
            + "   where t_finger_print_mashine.branch=:branch and DATE(ras_attrecord.Clock) =:date\n"
            + "   and ras_attrecord.is_in =:status and ras_attrecord.is_out = 0\n"
            + "   group by m_employee.index_no\n", nativeQuery = true)
    public List<Object> getAttendanceByDateAndStatusBranch(@Param("branch") Integer branch, @Param("date") String date, @Param("status") int status);

    @Query(value = "select ras_attrecord.* \n"
            + "from\n"
            + "ras_attrecord\n"
            + "LEFT JOIN\n"
            + "t_finger_print_mashine on t_finger_print_mashine.index_no=ras_attrecord.DN\n"
            + "WHERE ras_attrecord.is_in =:status \n"
            + "AND t_finger_print_mashine.branch =:branch \n"
            + "AND DATE(ras_attrecord.Clock) =:date ", nativeQuery = true)
    public List<TFingerPrint> findRasRecordsByDateAndBranch(@Param("branch") Integer branch, @Param("date") String date, @Param("status") int status);

}
